version: "3"
services:
  web.service:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: web-container
    ports:
      - 80:80
    volumes:
      - ./:/home/app
    tty: true
